export const SIGNUP_USER = 'SIGNUP_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'

export const GET_IMPRESSIONS = 'GET_IMPRESSIONS'
export const CREATE_IMPRESSION = 'CREATE_IMPRESSION'